// Embeds the browsercode-owned skills tree into the compiled bcode binary.
//
// The build script (`packages/opencode/script/build.ts`) calls
// `createEmbeddedSkillsBundle()` and plumbs the result into
// `Bun.build({ files: { "bcode-skills.gen.ts": <result> } })`. The generated
// virtual module exports `{ "<rel>": "<bunfs path>" }` for every file plus a
// content-hash `buildHash` used as the on-disk extraction sentinel.
// `skills.ts` reads it in compiled mode and extracts the files to
// `<dataDir>/skills/`, skipping when the sentinel matches.
//
// All skills are bcode-shipped read-only baseline — overwritten on every
// upgrade. (Phase H hard rule #3: there is no agent-editable surface here.
// The agent's editable surface is `<projectDir>/.bcode/agent-workspace/`,
// per-project, which never lands in the binary.)

import crypto from "crypto"
import fs from "fs/promises"
import path from "path"
import { fileURLToPath } from "url"

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const SKILLS_DIR = path.resolve(__dirname, "..", "skills")

// SHA-256 over (rel + NUL + content) for each file in sorted order. Stable
// across builds when content is identical, so warm launches skip extraction.
const computeBuildHash = async (files: string[]) => {
  const hash = crypto.createHash("sha256")
  for (const rel of files) {
    hash.update(rel)
    hash.update("\0")
    hash.update(await fs.readFile(path.join(SKILLS_DIR, rel)))
  }
  return hash.digest("hex")
}

export const createEmbeddedSkillsBundle = async (buildCwd: string) => {
  console.log("Embedding skills files into the binary")
  const files = (await Array.fromAsync(new Bun.Glob("**/*").scan({ cwd: SKILLS_DIR })))
    .map((file) => file.replaceAll("\\", "/"))
    .sort()

  console.log(`Embedding ${files.length} skills files`)
  const buildHash = await computeBuildHash(files)

  const imports = files.map((file, i) => {
    const spec = path.relative(buildCwd, path.join(SKILLS_DIR, file)).replaceAll("\\", "/")
    return `import file_${i} from ${JSON.stringify(spec.startsWith(".") ? spec : `./${spec}`)} with { type: "file" };`
  })
  const entries = files.map((file, i) => `  ${JSON.stringify(file)}: file_${i},`)
  return [
    `// Auto-generated by packages/bcode-browser/script/embed-skills.ts`,
    `// Maps "<rel>" -> bunfs path for every embedded skill file.`,
    ...imports,
    `export const buildHash = ${JSON.stringify(buildHash)}`,
    `export default {`,
    ...entries,
    `} as Record<string, string>`,
  ].join("\n")
}
